{
    "name": "Student Society Management",
    "version": "19.0.1.0.0",
    "category": "Productivity",
    "summary": "Membership, recruitment, lightweight projects, and connected accounts for a student consultancy",
    "author": "180 Degrees Consulting",
    "depends": [
        "base",
        "calendar",
        "contacts",
        "mail",
        "survey",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/res_partner_views.xml",
        "views/society_membership_views.xml",
        "views/society_recruitment_views.xml",
        "views/society_project_views.xml",
        "views/society_connected_account_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
    "license": "LGPL-3",
}
